name: Test Execution - Docker Compose

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository source code
      uses: actions/checkout@v3
    - name: Run Tests
      run: |
        docker compose -f test-service-docker-compose.yml
    - name: View Docker logs
      run: |
        docker compose logs -f
    - name: Compose down
      run: |
        docker compose down
      
